global:
  scrape_interval: 15s
  scrape_timeout: 10s

rule_files:
  - alert.yml

scrape_configs:
  - job_name: services
    metrics_path: /metrics
    static_configs:
      - targets:
          - 'prometheus:9090'
  - job_name: express_app
    metrics_path: /metrics
    static_configs:
      - targets:
          - '8180-221-124-123-242.ngrok.io'
