receivers:
  otlp:
    protocols:
      grpc:
      http:
        cors_allowed_origins:
          - http://*
          - https://*

exporters:
  jaeger:
    endpoint: jaeger-all-in-one:14250
    insecure: true

processors:
  batch:
  memory_limiter:
    # 75% of maximum memory up to 4G
    limit_mib: 1536
    # 25% of limit up to 2G
    spike_limit_mib: 512
    check_interval: 5s

service:
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [jaeger]
      processors: [memory_limiter, batch]
