version: '2'

networks:
  openplatform:

services:
  eventstore-cc1:
    image: ghcr.io/rtang03/eventstore-cc:0.0.6
    container_name: eventstore-cc1
    environment:
      - CHAINCODE_ADDRESS="0.0.0.0:7052"
      - CHAINCODE_CCID
    ports:
      - '7052:7052'
    networks:
      - openplatform
