version: '2'

networks:
  openplatform:

services:
  eventstore-cc2:
    image: ghcr.io/rtang03/eventstore-cc:0.0.6
    container_name: eventstore-cc2
    environment:
      - CHAINCODE_ADDRESS="0.0.0.0:7252"
      - CHAINCODE_CCID
    ports:
      - '7252:7252'
    networks:
      - openplatform
