version: '2.1'

networks:
  openplatform:

services:
  peer0org2.chaincode:
    image: ghcr.io/rtang03/eventstore-cc:0.0.6
    container_name: peer0org2.chaincode
    hostname: peer0org2.chaincode
    environment:
      - CHAINCODE_ADDRESS="peer0org2.chaincode:9999"
      - CHAINCODE_CCID
    ports:
      - '9999'
    networks:
      - openplatform
