channelName: loanapp
sync:
  syncDuration: 20
  requestTimeoutMs: 5000
  showStateChanges: true
  devMode: false
  persist: true
fabric:
  orgAdminId: admin-org1.net
  orgAdminSecret: admin-org1.netPW
  asLocalhost: true
  discovery: true
querydb:
  connectionName: 'default'
  schema: 'public'
  type: 'postgres'
  host: 'localhost'
  port: 15432
  database: 'eventstore'
  username: 'postgres'
  password: 'docker'
  logging: true
  connectTimeoutMS: 10000
metricserver:
  host: 'localhost'
  port: 9000
  interval: 1000
messageCenter:
  newCommitEndpoint:
  notifyNewCommit: false
  persist: true
  websocketEnabled: false
repo:
  requestTimeoutMs: 2000
